### ISSUE TITLE
Student Listing Page should have Search/Filters

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#107]
## Summary
Student Listing page should have these...
- Sort by Name
- Filter by Shelter
- Search by Name, ID

See the Volunteers > Search module on a sample of how this should be implemented.

## Page/Module
- Module: Student Listing
- URL: <https://makeadiff.in/madnet/#/students>
- File: src/pages/Students/Index.jsx

### Outcome
Users should be able to find the student details more easily - they shouldn't have to scroll and manually find the students.

**Comment by craterkamath** [comment]
Submitted PR #112  for the enhancements. Please review the code if possible @binnyva.
