### ISSUE TITLE
Volunteer Name Filter in Add to Batch Area

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#108]
## Summary

When adding volunteer to a batch, the person who's adding it should manually scroll thru all the volunteers to find the correct volunteer. Adding a name filter here will simplify this process - making it much easier to do.

![Current Situation](https://user-images.githubusercontent.com/8948/148941101-3018a640-be38-4f9b-a597-bcbd937073a6.png)

## Page/Module

Shelter > Teacher Assignment > Add New Teacher

File: src/pages/Allocations/Index.jsx

### Outcome

Something like this...

![A text field at the top that filters on keypress](https://user-images.githubusercontent.com/8948/148941410-4fc67f75-edaa-480e-828e-df799b81d133.png)

**Comment by Rhythm-26** [comment]
working on this

**Comment by Rhythm-26** [comment]
submitted PR#113
