### ISSUE TITLE
Donations : Detail View

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#34]
Option to click on donation to see more details

**Comment by binnyva** [comment]
Details to include...
- Donation ID
- Donor Name
- Fundraiser Name
- Amount
- Donation Date
- Donation Type

**Comment by binnyva** [comment]
When you go to <https://makeadiff.in/madnet/#/donations> you see all the donations you fund raised this year. Each donation should be clickable - and it should take you to a new page with all the details of the donation.

**Comment by Amrvp14** [comment]
i can work on it
