### ISSUE TITLE
Student Profile

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#66]
## Summary
Need a lot more details in the student page - their historical record with us. 

### Current

- Name
- Shelter/CCI
- Class - Level.grade
- Status
- Description
- Birthday
- Added On
- Notes
- Survey Results

### Year

- Class Section 
- Teacher(s)
- Classes Attended / Total
- Classes Absent
- Participation Average
- Survey Results

#### 2020

Same details as Year section

#### 2019

Same details as Year section

### All Time

- Teachers
- Class Attended / Total
- Participation Average

## Data Source

Use this GraphQL query...

```graphql
{
  student(id: 20631) {
    id
    name
    center {
      id name
    }
    comments {
      comment added_on 
      added_by_user { id name }
    }
    levels {
      id grade project_id year
      teachers {
     	  id name
      }
    }
    past_classes {
      id class_on class_type status 
      pivot {
        present
        participation
      }
    }
  }
}
```

## Page/Module
Student : View

### Outcome
We want new teachers to have this data easily so they can help the students better.

**Comment by craterkamath** [comment]
@binnyva  Can I take this up and work on improving the student view?

**Comment by craterkamath** [comment]
Additionally, I also noticed that the "Other Actions" form on the right panel doesn't have a close button. For a user without having write permission, the only way to close the opened list is to refresh the page. I have a simple commit here: 3cf0a4efb5e93bc6cd28c3fe291f554ae267fd91 that adds a close button. @binnyva  Can you please review this if possible?

Images for reference:

Before:

![Screenshot 2021-11-14 223817](https://user-images.githubusercontent.com/23616388/141691464-b0534a92-41eb-4914-b058-dc9e0c633fa6.png)

After:
![Screenshot 2021-11-14 223752](https://user-images.githubusercontent.com/23616388/141691473-eecb6c74-3f54-421a-a680-fc5b2f85e3dd.png)

**Comment by binnyva** [comment]
> @binnyva Can I take this up and work on improving the student view? Seems like a multi-parted issue which involves adding different components. I can knock them off one after another(Either in the same PR with chained commits or different PRs).

Someone is already working on this - can you take something else? Sorry about the confusion - I'll add people to the repo and assign tasks in a coupe of days.

That said, the close button is very useful. You can make a pull request for that.
