### ISSUE TITLE
Create an option to Delete existing batches

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#83]
## Summary
Create a button in the UI to delete batch. Use this call - [Delete Batch](http://makeadiff.in/api/api/swagger/doc.html#tag/batch%2Fpaths%2F~1batches~1%7Bbatch_id%7D%2Fdelete)
Only delete a batch if there is **no teachers assigned to it**. Do NOT delete used batches. If anyone wants to delete a batch, they have to remove all the allocations in that batch first.

## Page/Module
[Edit Batch Page](https://makeadiff.in/madnet/#/shelters/154/projects/1/batches/3592) - add an option to delete the batch here.

### Outcome
Right now there is no UI option to delete batch. Causes batches to build up in a shelter. Non-used batches can't be deleted without this.

**Comment by NayeBeckham** [comment]
Hello, I would like to contribute! Can I work on it?:)

**Comment by binnyva** [comment]
This is already done.
