### ISSUE TITLE
Create a test for shelter allocation / teacher allocation

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#86]
## Summary
Create Cypress integration test for the teacher assignment page. Copy over an existing test in the `MADNet/cypress/integration/` folder and build on that.

## Page/Module
[Teacher Assignment](https://makeadiff.in/madnet/#/shelters/154/projects/1/batch/0/level/0/view-teachers)

### Things to test
- Create new Assignment
- List assignment
- Edit existing
- Delete assignment

**Comment by irvinavelino** [comment]
Good afternoon, Id like to know if I can contribute with this issue

**Comment by binnyva** [comment]
Thanks for your offer. I'd suggest you start with the #84 issue - that might be easier to start with.

**Comment by irvinavelino** [comment]
ok i will look at that issue, thanks

**Comment by irvinavelino** [comment]
good evening, last time I made the #84 issue can I work on this one?

**Comment by binnyva** [comment]
Yes! Go for it :-D

**Comment by irvinavelino** [comment]
Good evening,i can't find the log in button, I see you made some changes nohow the page its seen, can you give me the url for logging in please?

**Comment by binnyva** [comment]
Thanks! Merged.
