### ISSUE TITLE
Ability to search volunteers by Shelter

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#88]
## Summary
You should be able to search for volunteers by a given shelter.

## Page/Module
[Volunteer Page](https://makeadiff.in/madnet/#/users) > Search
New search field should be in the More options section.

### Outcome
This will give you the ability to search/filter all the volunteers who belongs to a given shelter.

**Comment by jesusj0o** [comment]
Hello! I would like to work on this issue as well, can I give it a try?

**Comment by binnyva** [comment]
Sure. Go for it. And thanks :-D
You'll have to use the API to get some detail. API documentation is available at <http://makeadiff.in/api/api/swagger/doc.html>
First, find all the shelters in the city using this call - /cities/{city_id}/centers . (Shelters are called Centers in the api). Create a drop down with it to select from. 

For the searching, its the GET /users call - which is already used in the page. Just add the center_id parameter to it.

**Comment by binnyva** [comment]
Closed - https://github.com/makeadiff/Madnet/pull/96
