### ISSUE TITLE
New Class Section Create Form has a Delete Button

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#91]
**Describe the bug**
When creating a new Class section, there is a delete button visible. That button should not be there. It should be available only when editing a class section - not on creation.

**What page/module is the bug on?**
Shelter > Class Section > New. Eg. <https://makeadiff.in/madnet/#/shelters/244/projects/4/levels/0>

**Comment by jesusj0o** [comment]
Hello there! I would like to give this issue a try!

**Comment by binnyva** [comment]
Go for it @jesusj0o. Let me know if you have any doubts.

**Comment by jesusj0o** [comment]
Thank you @binnyva, should I have to create a user for the app or something?

**Comment by binnyva** [comment]
I'll give you the logins of a Demo user. What's your email id? I'm not sure if I can DM in github.

**Comment by jesusj0o** [comment]
thank you, you can use my email ***@***.*** as demo user

**Comment by binnyva** [comment]
That reply was edited by github to prevent sharing email, I guess. Can you send me an email? My email address is the same as my github username - in gmail. .

PS: The file you'll have to edit to fix this issue is  `src/pages/Levels/Form.jsx`

**Comment by jesusj0o** [comment]
you can send me the demo user to my email jesusjho26@gmail.com

**Comment by binnyva** [comment]
Done. I've mailed you the login details.

**Comment by binnyva** [comment]
Closing this. Thanks @jesusj0o :-D
