### ISSUE TITLE
Doesn't show message at sign in with a unknown user

### ISSUE THREAD

**Issue by NayeBeckham** [makeadiff/Madnet#97]
**Describe the bug**
The application doesn't show a message when the user is not registered at the moment to click on _sign in_ button. 

**What page/module is the bug on?**
Login page.

**To Reproduce**
Add your email in email/phone input.
Add your password in password input.
This bug is when both information is in the inputs.

**Expected behavior**
If the user is not recognized it should show a message to the user. The message only shows but in the console of developer tools.

**Comment by NayeBeckham** [comment]
I could work on this if you think it should be useful to the user! It should be a good first issue.

**Comment by binnyva** [comment]
Thank you :+1:
